version: '3'

networks:
  story_net:
    driver: bridge

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /ca_nhan/dbdata

services:
  # main database
  database:
    hostname: ${DATABASE_HOST}
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - story_net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  # backend
  backend:
    hostname: ${BACKEND_HOST}
    build: ./backend
    env_file:
      - ./.env
    networks:
      - story_net
    depends_on:
      - database
    ports:
      - '8080:8080'
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  # frontend
  frontend:
    hostname: ${FRONTEND_HOST}
    build: ./frontend
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - story_net
    ports:
      - '3000:3000'
  nginx:
    image: nginx
    hostname: proxy
    networks:
      - story_net
    restart: always
    volumes:
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/cert.crt
      - ./nginx/nginx-selfsigned.key:/etc/nginx/cert.key
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
